### PR TITLE
Removed typo

### PR DESCRIPTION
**Pull request by mhmoerma**
Remove the typo's ( _ instead of .)

### CODE REVIEW

**Review by merlijn-sebrechts — CHANGES_REQUESTED** [review]
I think you made a mistake during commit. Changes: `+3 −3,521`.

**Comment by mhmoerma** [comment]
I committed 2 times, since I forgot to do some removals to ensure this repo stays clean

**Comment by galgalesh** [comment]
This pull request removes `charms/xenial/sojobo-api` and all subdirectories. Is this intentional?

**Comment by mhmoerma** [comment]
Yes, I removed the builded version of this charm

**Pull request closed without merging**
